//
//  VGPConfig.h
//  VGPSDK
//
//  Created by  Tien Tran on 3/12/20.
//  Copyright © 2020  Tien Tran. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

#define _DEBUG_UI YES

#define VGP_EVENT_UPDATE_LANGUAGE @"VGP_EVENT_UPDATE_LANGUAGE"
#define VGP_EVENT_UPDATE_LAYOUT @"VGP_EVENT_UPDATE_LAYOUT"
#define VGP_EVENT_FACEBOOK_SHARE_SUCCESS @"VGP_EVENT_FACEBOOK_SHARE_SUCCESS"
#define VGP_EVENT_NETWORK_TIMEOUT @"VGP_EVENT_NETWORK_TIMEOUT"
#define VGP_EVENT_INIT_READY @"VGP_EVENT_INIT_READY"
#define VGP_EVENT_IFDA_REQUEST @"VGP_EVENT_IFDA_REQUEST"
#define VGP_EVENT_LOGIN_SUCCESS @"VGP_EVENT_LOGIN_SUCCESS"
#define VGP_EVENT_LOGOUT_SUCCESS @"VGP_EVENT_LOGOUT_SUCCESS"
#define VGP_EVENT_PURCHASE_SUCCESS @"VGP_EVENT_PURCHASE_SUCCESS"
#define VGP_EVENT_INFO_UPDATED @"VGP_EVENT_INFO_UPDATED"

@interface VGPConfig : NSObject

extern NSString *VGP_SERVER;
extern NSString *VGP_GAMEID;

extern NSString *VGP_APP_ID;
extern NSString *VGP_TIKTOK_APP_ID;
extern NSString *VGP_TIKTOK_LEVEL_UP;

extern NSString *VGP_SDK_VERSION;
extern NSString *VGP_APPTOKEN;
extern NSString *VGP_ENDPOINT;

extern BOOL VGP_APPS_ADJUST_DEBUG;
extern NSString *VGP_APPS_ADJUST_APP_TOKEN;
extern NSString *VGP_APPS_ADJUST_EVENT_LAUNCH_APP_TOKEN;
extern NSString *VGP_APPS_ADJUST_EVENT_CREATED_CHARACTER_TOKEN;
extern NSDictionary *VGP_APPS_ADJUST_EVENT_LEVEL_TOKEN;
extern NSString *VGP_APPS_ADJUST_EVENT_PURCHASE_TOKEN;
extern NSString* VGP_APPS_ADJUST_EVENT_SIGNIN_SUCCESS_TOKEN;
extern NSString *VGP_APPS_ADJUST_EVENT_SIGNUP_SUCCESS_TOKEN;

extern NSString* VGP_APPS_ADJUST_VERSION;
extern NSString* VGP_APPS_ADJUST_ADID;

extern NSString *VGP_BANNER;
extern NSString *VGP_BANNER_DEVICE_WHITELIST;
extern NSString *VGP_LANG;
extern BOOL VGP_CONFIG_LOADED;
extern NSString *VGP_CLIENT_SDK_VERSION;
extern NSString* SOCKET_ID;
extern NSString *SOCKET_STATUS;

extern UIColor *VGP_MAIN_TEXT_COLOR;

extern NSArray* VGP_IAP_ITEMS;
extern BOOL VGP_SHOW_LOG;
extern BOOL VGP_FACEBOOK_PURCHASE_EVENT;
extern BOOL VGP_FIREBASE_PURCHASE_EVENT;
extern BOOL VGP_ADJUST_PURCHASE_EVENT;

/*!
 @todo Autoload method
*/
+ (void)load;
+ (void)load:(void (^ __nullable)(void))completion;

@end

NS_ASSUME_NONNULL_END
